namePrefix: dev-
commonLabels:
  variant: development
images:
- name: quay.io/dhanamjaya/do400-deploying-environments
  newTag: latest
patches:
- patch: |-
    - op: replace
      path: /spec/to/name
      value: dev-simple
  target:
    kind: Route
apiVersion: v1
kind: Kustomization
resources:
- "../../base"
